default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: conventional-commit
        name: conventional commit message
        entry: python3 .github/scripts/check-conventional-commit.py
        language: system
        stages: [commit-msg]
