name: CD

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "scripts/**"
      - ".cargo/config.toml"
      - ".github/workflows/cd.yaml"
      - ".github/workflows/publish-cli-artifactory.yaml"

permissions:
  contents: write

jobs:
  tag-and-release:
    uses: comcast-zorrillo/gha-reusable-workflows/.github/workflows/tag-and-release.yaml@v0.0.3-tag-and-release
    with:
      prerelease: true

  publish-cli-artifactory:
    needs: tag-and-release
    uses: ./.github/workflows/publish-cli-artifactory.yaml
    with:
      version_tag: ${{ needs.tag-and-release.outputs.version-tag }}
      runner_label: comcast-ubuntu-latest
      timeout_minutes: 20
      allow_existing: false
    secrets:
      artifactory_token: ${{ secrets.ARTIFACTORY_TITAN_CARGO_PASSWORD }}
